version: "3"

services:
  database:
    image: "postgres:latest"
    container_name: pg_ml_project
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./data:/docker-entrypoint-initdb.d

networks:
  postgres-network:
    driver: bridge
