version: "3"

services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d

networks:
  postgres-network:
    driver: bridge
